Regular Exam 20240218/Task-2/URLShortener/Models/URLAddresses/URLAddressFormModel.cs
using System.ComponentModel.DataAnnotations;

using static URLShortenerData.Data.DataConstants;

namespace URLShortener.Models.URLAddresses
{
    public class URLAddressFormModel
    {
        [Required]
        [MaxLength(OriginalUrlMaxLenght)]
        [MinLength(OriginalUrlMinLenght)]
        public string URL { get; init; } = null!;

        [Required]
        [MaxLength(ShortUrlMaxLenght)]
        [MinLength(ShortUrlMinLenght)]
	    [Display(Name = "short code")]
        public string ShortCode { get; init; } = null!;
    }
}

Regular Exam 20240218/Task-2/URLShortener/Models/URLAddresses/URLAddressViewModel.cs
namespace URLShortener.Models.URLAddresses
{
    public class URLAddressViewModel
    {
        public int Id { get; init; }

        public string OriginalUrl { get; set; } = null!;

        public string ShortUrl { get; set; } = null!;

        public DateTime DateCreated { get; set; }

        public int Visits { get; set; }

    }
}

Regular Exam 20240218/Task-2/URLShortener/Controllers/URLAddressController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using URLShortener.Infrastructure;
using URLShortener.Models.URLAddresses;

using URLShortenerData.Data;
using URLShortenerData.Data.Entities;

namespace URLShortener.Controllers
{
    public class URLAddressController : Controller
    {
        private readonly URLShortenerDbContext context;

        public URLAddressController(URLShortenerDbContext data)
        {
            this.context = data;
        }

        public IActionResult All()
        {
            List<URLAddressViewModel> urlAddresses = this.context.URLAddresses
                .Select(x => new URLAddressViewModel
            {
                Id = x.Id,
                OriginalUrl = x.OriginalUrl,
                ShortUrl = x.ShortUrl,
                DateCreated = x.DateCreated,
                Visits = x.Visits
            }).ToList();

            return this.View(urlAddresses);
        }

        [Authorize]
        public IActionResult Add()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(URLAddressFormModel model)
        {
            if (this.context.URLAddresses.Any(c => c.OriginalUrl == model.URL && c.UserId == this.User.UserId()))
            {
                this.ModelState.AddModelError(nameof(model.URL),
                    "You already have a short URL of that original URL!");
            }

            if (this.context.URLAddresses.Any(c => c.ShortUrl.Contains(model.ShortCode)))
            {
                this.ModelState.AddModelError(nameof(model.ShortCode),
                    $"A short code \"{model.ShortCode}\" already exists!");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            URLAddress url = new URLAddress
            {
                OriginalUrl = model.URL,
                ShortUrl = "http://shorturl.nakov.repl.co/go/" + model.ShortCode,
                DateCreated = DateTime.UtcNow,
                UserId = this.User.UserId(),
                Visits = 0
            };

            this.context.URLAddresses.Add(url);
            this.context.SaveChanges();

            return this.RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            if (!this.URLExists(id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            URLAddress? url = this.GetURLAddressById(id);
            if (url is null)
            {
                return this.NotFound();
            }

            string theOriginalShortCode = url.ShortUrl.Substring(url.ShortUrl.LastIndexOf('/') + 1);

            URLAddressFormModel urlFormModel = new URLAddressFormModel()
            {
                URL = url.OriginalUrl,
                ShortCode = theOriginalShortCode
            };

            return this.View(urlFormModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, URLAddressFormModel model)
        {
            if (!this.URLExists(id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            URLAddress? url = this.GetURLAddressById(id);
            if (url is null)
            {
                return this.NotFound();
            }

            url.OriginalUrl = model.URL;
            url.ShortUrl = url.ShortUrl.Substring(0, url.ShortUrl.LastIndexOf('/') + 1) + model.ShortCode;

            this.context.SaveChanges();

            return this.RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            if (!this.URLExists(id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            URLAddress? urlData = this.GetURLAddressById(id);
            if (urlData == null)
            {
                return this.BadRequest();
            }

            URLAddressViewModel model = new URLAddressViewModel()
            {
                Id = urlData.Id,
                OriginalUrl = urlData.OriginalUrl,
                ShortUrl = urlData.ShortUrl,
                DateCreated = urlData.DateCreated,
                Visits = urlData.Visits
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(URLAddressViewModel model)
        {
            if (!this.URLExists(model.Id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(model.Id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            URLAddress? urlAddress = this.GetURLAddressById(model.Id);
            if (urlAddress is null)
            {
                return this.NotFound();
            }

            this.context.URLAddresses.Remove(urlAddress);
            this.context.SaveChanges();

            return this.RedirectToAction("Index", "Home");
        }

        public bool URLExists(int id)
        {
            return this.context.URLAddresses.Any(h => h.Id == id);
        }

        public bool UserIsCreator(int urlId, string userId)
        {
            URLAddress? urlAddress = this.context.URLAddresses.FirstOrDefault(a => a.Id == urlId);
            if (urlAddress is null)
            {
                return false;
            }

            return urlAddress.UserId == userId;
        }

        public URLAddress? GetURLAddressById(int id)
        {
            URLAddress? address = this.context.URLAddresses.Find(id);
            if (address is null)
            {
                return null;
            }

            return address;
        }

        [HttpGet("URLAddressController/RedirectTo/{path:required}", Name = "ShortUrls_RedirectTo")]
        public IActionResult RedirectTo(string path)
        {
            if (path is null)
            {
                return this.NotFound();
            }

            string normalizeUrl = path.Replace("%2F", "/");

            URLAddress urlOriginalAddres = this.context.URLAddresses
                .FirstOrDefault(a => a.ShortUrl == normalizeUrl)!;
            if (urlOriginalAddres.OriginalUrl is null)
            {
                return this.NotFound();
            }

            urlOriginalAddres.Visits++;
            this.context.SaveChanges();

            return this.Redirect(urlOriginalAddres.OriginalUrl);
        }
    }
}

Regular Exam 20240218/Task-2/URLShortener/Views/URLAddress/Add.cshtml
@model URLAddressFormModel

@{
    ViewBag.Title = "Add URL Address";
}

<h1 class="display-4" id="headerText">Add Short URL</h1>

<partial name="_URLAddressFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Regular Exam 20240218/Task-2/URLShortener/Views/URLAddress/All.cshtml
@model IEnumerable<URLAddressViewModel>

@{
    ViewBag.Title = "All URL Addresses";
}
<div class="text-center">
    <h1 class="display-4" id="headerText">Short URLs</h1>
    <div class="scrollit">
        <table class="urls">
            <thead>
                <tr>
                    <th>Original URL</th>
                    <th>Short URL</th>
                    <th>Date Created</th>
                    <th>Visits</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var url in Model)
                {
                    <tr>
                        <td>
                            <a href="@url.OriginalUrl" target="_blank">@url.OriginalUrl</a>
                        </td>
                        <td>
                            <a class="shorturl" method="get" asp-controller="URLAddress" asp-action="RedirectTo" asp-route-path="@url.ShortUrl">@url.ShortUrl</a>
                        </td>
                        <td>@url.DateCreated.ToString("yyyy/MM/dd HH:mm:ss")</td>
                        <td>@url.Visits</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Regular Exam 20240218/Task-2/URLShortener/Views/URLAddress/Delete.cshtml
@model URLAddressViewModel

@{
    ViewBag.Title = "Delete URL Address";
}

<div class="text-center">
    <h1 class="display-4" id="headerText">Delete Short URL</h1>
    <div >
        <form asp-action="Delete">
            <table class="urls" style="max-width:1000px">
                <thead>
                    <tr>
                        <th>Original URL</th>
                        <th>Short URL</th>
                        <th>Date Created</th>
                        <th>Visits</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <label asp-for="OriginalUrl" href="@Model.OriginalUrl" target="_blank">@Model.OriginalUrl</label>
                        </td>
                        <td>
                            <label asp-for="ShortUrl" class="shorturl" method="get" asp-controller="URLAddress" asp-action="RedirectTo" asp-route-path="@Model.ShortUrl">@Model.ShortUrl</label>
                        </td>
                        <td><label asp-for="DateCreated">@Model.DateCreated.ToString("yyyy/MM/dd HH:mm:ss")</label></td>
                        <td><label asp-for="Visits">@Model.Visits</label></td>
                        <td>
                            <button id="deleteBtn" type="submit">Delete</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>

Regular Exam 20240218/Task-2/URLShortener/Views/URLAddress/Edit.cshtml
@model URLAddressFormModel

@{
    ViewBag.Title = "Edit URL Address";
}

<h1 class="display-4" id="headerText">Edit Short URL</h1>

<partial name="_URLAddressFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Regular Exam 20240218/Task-2/URLShortener/Views/URLAddress/_URLAddressFormPartial.cshtml
@model URLAddressFormModel

<form method="POST">
        <table>
            <tbody>
                <tr>
                    <td>
                        <label class="url" for="url" asp-for="URL">URL: </label>
                    </td>
                    <td>
                        <input id="url" type="text" asp-for="URL">
                        <span asp-validation-for="URL" class="small text-danger"></span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label class="code" for="code" asp-for="ShortCode">Short Code: </label>
                    </td>
                    <td>
                        <input id="code" type="text" asp-for="ShortCode">
                        <span asp-validation-for="ShortCode" class="small text-danger"></span>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                    <button id="button" type="submit">Submit</button>
                    </td>
                </tr>
            </tbody>
        </table>
</form>